### ISSUE TITLE
Domain not exists

### ISSUE THREAD

**Issue by devashish2024** [RedGuy12/OneAuth#66]
### Is there an existing issue for this?

- [x] I have searched the existing issues and none does.

### Describe the bug

Please solve the domain, it does not exist. How to use this locally?

### To reproduce

1. Go to…
2. Click on…
3. See error

### Expected behavior

null

### Branch

develop

### Browser

Chromium

### OS

Windows

### Agree to our policies

- [X] I agree to follow the [Code of Conduct](https://github.com/onedotprojects/auth/blob/issues/.github/CODE_OF_CONDUCT.md).
- [X] I agree to follow the [Contributing Guidelines](https://github.com/onedotprojects/auth/blob/issues/.github/CONTRIBUTING.md).
- [ ] I am willing to submit a PR to fix this (optional).

**Comment by cobaltt7** [comment]
this is dead

**Comment by retronbv** [comment]
:shipit:

**Comment by devashish2024** [comment]
Well, how to run locally using npm

**Comment by retronbv** [comment]
> Well, how to run locally using npm

Well, try to read `package.json` 🙄 
`npm run start` should do the trick

**Comment by cobaltt7** [comment]
> > Well, how to run locally using npm
> 
> Well, try to read `package.json` 🙄 `npm run start` should do the trick

well actually just `npm i && npm start`

although you'd need all the many environment variables

and even after that, I'm not sure how broken this is rn

**Comment by devashish2024** [comment]
oh
